// Base de datos de todo el plantel
const baseJugadores = {
  "guerreiro": {
    nombre: "Joaquin Guerreiro",
    dorsal: "1",
    posicion: "Arquero",
    foto: "imagenes/plantel/joaquin1.png",
    edad: "21 años",
    trayectoria: "El Tanque de Guerra ",
    stats: { goles: 0, asistencias: 0, pj: 7, ta: 1, tr: 0 },
    instagram: "joaguerreiro",
    localidad: "Rada Tilly",
  },
    "ibanez": {
    nombre: "Mateo Ibañez",
    dorsal: "25",
    posicion: "Central",
    foto: "imagenes/plantel/mateo1.png",
    edad: "22 años",
    trayectoria: "El Terror de los Delanteros",
    stats: { goles: 1, asistencias: 0, pj: 7, ta: 1, tr: 0 },
    instagram: "mate_iba",
    localidad: "Bariloche",
  },
    "fuentealba": {
    nombre: "Agustin Fuentealba",
    dorsal: "6",
    posicion: "Central",
    foto: "imagenes/plantel/agustin1.png",
    edad: "22 años",
    trayectoria: "Carnicero del Area",
    stats: { goles: 0, asistencias: 0, pj: 6, ta: 0, tr: 0 },
    instagram: "aguusfuentealba",
    localidad: "General Roca",
  },
    "fmorbiducci": {
    nombre: "Francesco Morbiducci",
    dorsal: "13",
    posicion: "Lateral / Central",
    foto: "imagenes/plantel/francesco.png",
    edad: "22 años",
    trayectoria: "Patovica del Carril Izquierdo",
    stats: { goles: 0, asistencias: 0, pj: 7, ta: 1, tr: 0 },
    instagram:"franmorbiducci",
    localidad:"Saladillo"
  },
    "dgonzalez": {
    nombre: "Daniel Gonzalez",
    dorsal: "17",
    posicion: "Lateral / Central",
    foto: "imagenes/plantel/daniel1.png",
    edad: "22 años",
    trayectoria: "El Asesino de la banda derecha",
    stats: { goles: 0, asistencias: 0, pj: 7, ta: 0, tr: 0 },
    instagram: "panchigonzalez_",
    localidad: "-",
  },
    "buroni": {
    nombre: "Uriel Buroni",
    dorsal: "80",
    posicion: "V. Central / V. Interior",
    foto: "imagenes/plantel/uriel1.png",
    edad: "22 años",
    trayectoria: "Magia y Gambeta",
    stats: { goles: 0, asistencias: 0, pj: 6, ta: 0, tr: 0 },
    instagram: "uriiel.buroni",
    localidad: "Punta Lara",
  },
    "millar": {
    nombre: "Jeremias Millar",
    dorsal: "30",
    posicion: "V. Interior / Mediapunta",
    foto: "imagenes/plantel/jere1.png",
    edad: "22 años",
    trayectoria: "Atrevido y Encarador",
    stats: { goles: 2, asistencias: 0, pj: 5, ta: 0, tr: 0 },
    instagram: "jeremiassmillar",
    localidad: "Del Sur",
  },
    "emorbiducci": {
    nombre: "Enzo Morbiducci",
    dorsal: "5",
    posicion: "V. Central / Mediapunta",
    foto: "imagenes/plantel/enzo1.png",
    edad: "22 años",
    trayectoria: "El Caudillo",
    stats: { goles: 0, asistencias: 0, pj: 7, ta: 4, tr: 1 },
    instagram: "enzomorbiducci",
    localidad: "Saladillo",
  },
    "rubio": {
    nombre: "Santiago Rubio",
    dorsal: "20",
    posicion: "Mediapunta / V. Interior",
    foto: "imagenes/plantel/rubio_ia.png",
    edad: "22 años",
    trayectoria: "El Imán de la Pelota",
    stats: { goles: 0, asistencias: 0, pj: 3, ta: 0, tr: 0 },
    instagram: "ssantiagorubio_",
    localidad: "-",
  },
    "morante": {
    nombre: "Dante Morante",
    dorsal: "22",
    posicion: "Carrilero / Extremo",
    foto: "imagenes/plantel/dante1.png",
    edad: "22 años",
    trayectoria: "-",
    stats: { goles: 0, asistencias: 0, pj: 5, ta: 1, tr: 0 },
    instagram: "dannmorantee",
    localidad: "25 de Mayo",
  },
    "perez": {
    nombre: "Tomas Perez",
    dorsal: "16",
    posicion: "Carrilero / Extremo",
    foto: "imagenes/plantel/tomas1.png",
    edad: "22 años",
    trayectoria: "El de los momentos importantes",
    stats: { goles: 2, asistencias: 0, pj: 6, ta: 0, tr: 0 },
    instagram: "tomi_perez27",
    localidad: "-",
  },
    "giusso": {
    nombre: "Alvaro Giusso",
    dorsal: "7",
    posicion: "Carrilero / Extremo",
    foto: "imagenes/plantel/alvaro_ia.png",
    edad: "22 años",
    trayectoria: "El Motorcito",
    stats: { goles: 0, asistencias: 0, pj: 6, ta: 0, tr: 1 },
    instagram: "alvarogiusso",
    localidad: "25 de Mayo",
  },
    "dome": {
    nombre: "Julian Dome",
    dorsal: "18",
    posicion: "Carrilero / Mediapunta",
    foto: "imagenes/plantel/juli1.png",
    edad: "22 años",
    trayectoria: "Zurdito Habilidoso",
    stats: { goles: 0, asistencias: 0, pj: 4, ta: 0, tr: 0 },
    instagram: "juli_dome",
    localidad: "-",
  },
    "basualdo": {
    nombre: "Santiago Basualdo",
    dorsal: "8",
    posicion: "Interior / D. Centro",
    foto: "imagenes/plantel/basu1.png",
    edad: "22 años",
    trayectoria: "La Máquina",
    stats: { goles: 2, asistencias: 1, pj: 6, ta: 2, tr: 1 },
    instagram: "santi_basualdo.7",
    localidad: "25 de Mayo",
  },
    "cisint": {
    nombre: "Lautaro Cisint",
    dorsal: "10",
    posicion: "Mediapunta / D. Centro",
    foto: "imagenes/plantel/lautaro1.png",
    edad: "22 años",
    trayectoria: "El Diez",
    stats: { goles: 0, asistencias: 0, pj: 7, ta: 1, tr: 1 },
    instagram: "lautarocisint",
    localidad: "General Roca",
  },
    "vivar": {
    nombre: "Francisco Vivar",
    dorsal: "69",
    posicion: "Delantero Centro",
    foto: "imagenes/plantel/franvivar1.png",
    edad: "22 años",
    trayectoria: "Mr. Músculo",
    stats: { goles: 1, asistencias: 2, pj: 7, ta: 0, tr: 0 },
    instagram: "franciscovivaar",
    localidad: "Algun lugar de la Patagonia",
  },
    "fpaz": {
    nombre: "Fernanda Paz",
    dorsal: "-",
    posicion: "-",
    foto: "imagenes/plantel/fpaz.png",
    edad: "22 años",
    trayectoria: "Capturadora de recuerdos",
    instagram: "fpazph",
    localidad: "Bolívar",
  },
    "vento": {
    nombre: "Livio Vento",
    dorsal: "-",
    posicion: "-",
    foto: "imagenes/plantel/generico.png",
    edad: "22 años",
    trayectoria: "Preparador Físico",
    instagram: "livio.vento",
    localidad: "Rada Tilly",
  },
  // Aca voy a seguir agregando a los otros 14 copiando esta estructura...
};