// Base de datos de todo el plantel
const baseJugadores = {
  "guerreiro": {
    nombre: "Joaquin Guerreiro",
    dorsal: "1",
    posicion: "Arquero",
    foto: "imagenes/plantel/joaquin1.png",
    edad: "21 años",
    trayectoria: "El Tanque de Guerra ",
    stats: { goles: 0, asistencias: 0, pj: 7, ta: 1, tr: 0 },
    instagram: "joaguerreiro",
    localidad: "Rada Tilly",
  },
    "ibanez": {
    nombre: "Mateo Ibañez",
    dorsal: "25",
    posicion: "Central",
    foto: "imagenes/plantel/mateo1.png",
    edad: "22 años",
    trayectoria: "El Terror de los Delanteros",
    stats: { goles: 1, asistencias: 0, pj: 7, ta: 1, tr: 0 },
    instagram: "mate_iba",
    localidad: "Bariloche",
  },
    "fuentealba": {
    nombre: "Agustin Fuentealba",
    dorsal: "6",
    posicion: "Central",
    foto: "imagenes/plantel/agustin1.png",
    edad: "22 años",
    trayectoria: "Carnicero del Area",
    stats: { goles: 0, asistencias: 0, pj: 6, ta: 0, tr: 0 },
    instagram: "aguusfuentealba",
    localidad: "General Roca",
  },
    "fmorbiducci": {
    nombre: "Francesco Morbiducci",
    dorsal: "13",
    posicion: "Lateral / Central",
    foto: "imagenes/plantel/francesco.png",
    edad: "22 años",
    trayectoria: "Patovica del Carril Izquierdo",
    stats: { goles: 0, asistencias: 0, pj: 7, ta: 1, tr: 0 },
    instagram:"franmorbiducci",
    localidad:"Saladillo"
  },
    "dgonzalez": {
    nombre: "Daniel Gonzalez",
    dorsal: "17",
    posicion: "Lateral / Central",
    foto: "imagenes/plantel/daniel1.png",
    edad: "22 años",
    trayectoria: "El Asesino de la banda derecha",
    stats: { goles: 0, asistencias: 0, pj: 7, ta: 0, tr: 0 },
    instagram: "panchigonzalez_",
    localidad: "-",
  },
    "buroni": {
    nombre: "Uriel Buroni",
    dorsal: "80",
    posicion: "V. Central / V. Interior",
    foto: "imagenes/plantel/uriel1.png",
    edad: "22 años",
    trayectoria: "Magia y Gambeta",
    stats: { goles: 0, asistencias: 0, pj: 6, ta: 0, tr: 0 },
    instagram: "uriiel.buroni",
    localidad: "Punta Lara",
  },
    "millar": {
    nombre: "Jeremias Millar",
    dorsal: "30",
    posicion: "V. Interior / Mediapunta",
    foto: "imagenes/plantel/jere1.png",
    edad: "22 años",
    trayectoria: "Atrevido y Encarador",
    stats: { goles: 2, asistencias: 0, pj: 5, ta: 0, tr: 0 },
    instagram: "jeremiassmillar",
    localidad: "Del Sur",
  },
    "emorbiducci": {
    nombre: "Enzo Morbiducci",
    dorsal: "5",
    posicion: "V. Central / Mediapunta",
    foto: "imagenes/plantel/enzo1.png",
    edad: "22 años",
    trayectoria: "El Caudillo",
    stats: { goles: 0, asistencias: 0, pj: 7, ta: 4, tr: 1 },
    instagram: "enzomorbiducci",
    localidad: "Saladillo",
  },
    "fpaz": {
    nombre: "Fernanda Paz",
    dorsal: "-",
    posicion: "-",
    foto: "imagenes/plantel/fpaz.png",
    edad: "22 años",
    trayectoria: "Capturadora de recuerdos",
    instagram: "fpazph",
    localidad: "Bolívar",
    },
  // Aca voy a seguir agregando a los otros 14 copiando esta estructura...
};